name: deploy

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'

jobs:
  deploy-env:
    runs-on: ubuntu-latest

    steps:
      - name: Démarrage déploiement
        run: echo "Démarrage du workflow sur ${{ github.ref }}"
        
      - name: Récupération code
        uses: actions/checkout@v4.1.1
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: prod
        run: echo "Environnement de production choisi"
        if: ${{ github.event.inputs.server == 'prod' }} 

      - name: qual
        run: |
          echo "Environnement de qualification choisi"
          exit 1
        if: ${{ github.event.inputs.server == 'qual' }} 

      - name: dev
        run: echo "Environnement de développement choisi"
        if: ${{ github.event.inputs.server == 'dev' }} 

      - name : Fin de workflow 
        run: echo "Fin de workflow"
        if: always() 

       
